[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_sohail = "GZtp8KcthweXo1brnJtMvb8EV5bZYK92pWbrCBqiMDom"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sohail/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
